<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ZConfigPhdSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('z_config_phd')->insert([
            ['phd_id' => 1, 'cloud_id' => 0, 'phd_name' => 'Other Doctorate', 'phd_parent_id' => 0],
            ['phd_id' => 2, 'cloud_id' => 0, 'phd_name' => 'M.Phil.', 'phd_parent_id' => 0],
            ['phd_id' => 3, 'cloud_id' => 0, 'phd_name' => 'Ph.D', 'phd_parent_id' => 0],
            ['phd_id' => 4, 'cloud_id' => 0, 'phd_name' => 'Any Doctorate', 'phd_parent_id' => 0],
            ['phd_id' => 5, 'cloud_id' => 0, 'phd_name' => 'Doctorate Not Required', 'phd_parent_id' => 0],
            ['phd_id' => 6, 'cloud_id' => 0, 'phd_name' => 'None', 'phd_parent_id' => 5],
            ['phd_id' => 8, 'cloud_id' => 0, 'phd_name' => 'Any Specialization', 'phd_parent_id' => 4],
            ['phd_id' => 9, 'cloud_id' => 0, 'phd_name' => 'Advertising / Mass Communication', 'phd_parent_id' => 3],
            ['phd_id' => 10, 'cloud_id' => 0, 'phd_name' => 'Agriculture', 'phd_parent_id' => 3],
            ['phd_id' => 11, 'cloud_id' => 0, 'phd_name' => 'Anthropology', 'phd_parent_id' => 3],
            ['phd_id' => 12, 'cloud_id' => 0, 'phd_name' => 'Architecture', 'phd_parent_id' => 3],
            ['phd_id' => 13, 'cloud_id' => 0, 'phd_name' => 'Arts & Humanities', 'phd_parent_id' => 3],
            ['phd_id' => 14, 'cloud_id' => 0, 'phd_name' => 'Automobile', 'phd_parent_id' => 3],
            ['phd_id' => 15, 'cloud_id' => 0, 'phd_name' => 'Aviation', 'phd_parent_id' => 3],
            ['phd_id' => 16, 'cloud_id' => 0, 'phd_name' => 'Bio-Chemistry / Bio-Technology', 'phd_parent_id' => 3],
            ['phd_id' => 17, 'cloud_id' => 0, 'phd_name' => 'Biomedical', 'phd_parent_id' => 3],
            ['phd_id' => 18, 'cloud_id' => 0, 'phd_name' => 'Biotechnology', 'phd_parent_id' => 3],
            ['phd_id' => 19, 'cloud_id' => 0, 'phd_name' => 'Ceramics', 'phd_parent_id' => 3],
            ['phd_id' => 20, 'cloud_id' => 0, 'phd_name' => 'Chemical', 'phd_parent_id' => 3],
            ['phd_id' => 21, 'cloud_id' => 0, 'phd_name' => 'Chemistry', 'phd_parent_id' => 3],
            ['phd_id' => 22, 'cloud_id' => 0, 'phd_name' => 'Civil', 'phd_parent_id' => 3],
            ['phd_id' => 23, 'cloud_id' => 0, 'phd_name' => 'Commerce', 'phd_parent_id' => 3],
            ['phd_id' => 24, 'cloud_id' => 0, 'phd_name' => 'Communication', 'phd_parent_id' => 3],
            ['phd_id' => 25, 'cloud_id' => 0, 'phd_name' => 'Computers', 'phd_parent_id' => 3],
            ['phd_id' => 26, 'cloud_id' => 0, 'phd_name' => 'Dairy Technology', 'phd_parent_id' => 3],
            ['phd_id' => 27, 'cloud_id' => 0, 'phd_name' => 'Dermatology', 'phd_parent_id' => 3],
            ['phd_id' => 28, 'cloud_id' => 0, 'phd_name' => 'Economics', 'phd_parent_id' => 3],
            ['phd_id' => 29, 'cloud_id' => 0, 'phd_name' => 'Electrical', 'phd_parent_id' => 3],
            ['phd_id' => 30, 'cloud_id' => 0, 'phd_name' => 'Electronics / Telecommunication', 'phd_parent_id' => 3],
            ['phd_id' => 31, 'cloud_id' => 0, 'phd_name' => 'Energy', 'phd_parent_id' => 3],
            ['phd_id' => 32, 'cloud_id' => 0, 'phd_name' => 'ENT', 'phd_parent_id' => 3],
            ['phd_id' => 33, 'cloud_id' => 0, 'phd_name' => 'Environmental', 'phd_parent_id' => 3],
            ['phd_id' => 34, 'cloud_id' => 0, 'phd_name' => 'Fashion Designing / Other Designing', 'phd_parent_id' => 3],
            ['phd_id' => 35, 'cloud_id' => 0, 'phd_name' => 'Film', 'phd_parent_id' => 3],
            ['phd_id' => 36, 'cloud_id' => 0, 'phd_name' => 'Finance', 'phd_parent_id' => 3],
            ['phd_id' => 37, 'cloud_id' => 0, 'phd_name' => 'Fine arts', 'phd_parent_id' => 3],
            ['phd_id' => 38, 'cloud_id' => 0, 'phd_name' => 'Food Technology', 'phd_parent_id' => 3],
            ['phd_id' => 39, 'cloud_id' => 0, 'phd_name' => 'Hotel Management', 'phd_parent_id' => 3],
            ['phd_id' => 40, 'cloud_id' => 0, 'phd_name' => 'History', 'phd_parent_id' => 3],
            ['phd_id' => 41, 'cloud_id' => 0, 'phd_name' => 'HR / Industrial Relations', 'phd_parent_id' => 3],
            ['phd_id' => 42, 'cloud_id' => 0, 'phd_name' => 'Immunology', 'phd_parent_id' => 3],
            ['phd_id' => 43, 'cloud_id' => 0, 'phd_name' => 'International Business', 'phd_parent_id' => 3],
            ['phd_id' => 44, 'cloud_id' => 0, 'phd_name' => 'Instrumentation', 'phd_parent_id' => 3],
            ['phd_id' => 45, 'cloud_id' => 0, 'phd_name' => 'Journalism', 'phd_parent_id' => 3],
            ['phd_id' => 46, 'cloud_id' => 0, 'phd_name' => 'Law', 'phd_parent_id' => 3],
            ['phd_id' => 47, 'cloud_id' => 0, 'phd_name' => 'Literature', 'phd_parent_id' => 3],
            ['phd_id' => 48, 'cloud_id' => 0, 'phd_name' => 'Marine', 'phd_parent_id' => 3],
            ['phd_id' => 49, 'cloud_id' => 0, 'phd_name' => 'Marketing', 'phd_parent_id' => 3],
            ['phd_id' => 50, 'cloud_id' => 0, 'phd_name' => 'Maths', 'phd_parent_id' => 3],
            ['phd_id' => 51, 'cloud_id' => 0, 'phd_name' => 'Mechanical', 'phd_parent_id' => 3],
            ['phd_id' => 52, 'cloud_id' => 0, 'phd_name' => 'Medicine', 'phd_parent_id' => 3],
            ['phd_id' => 53, 'cloud_id' => 0, 'phd_name' => 'Metallurgy', 'phd_parent_id' => 3],
            ['phd_id' => 54, 'cloud_id' => 0, 'phd_name' => 'Microbiology', 'phd_parent_id' => 3],
            ['phd_id' => 55, 'cloud_id' => 0, 'phd_name' => 'Mineral', 'phd_parent_id' => 3],
            ['phd_id' => 56, 'cloud_id' => 0, 'phd_name' => 'Mining', 'phd_parent_id' => 3],
            ['phd_id' => 57, 'cloud_id' => 0, 'phd_name' => 'Neonatal', 'phd_parent_id' => 3],
            ['phd_id' => 58, 'cloud_id' => 0, 'phd_name' => 'Nuclear', 'phd_parent_id' => 3],
            ['phd_id' => 59, 'cloud_id' => 0, 'phd_name' => 'Obstetrics', 'phd_parent_id' => 3],
            ['phd_id' => 60, 'cloud_id' => 0, 'phd_name' => 'Paint / Oil', 'phd_parent_id' => 3],
            ['phd_id' => 61, 'cloud_id' => 0, 'phd_name' => 'Pathology', 'phd_parent_id' => 3],
            ['phd_id' => 62, 'cloud_id' => 0, 'phd_name' => 'Petroleum', 'phd_parent_id' => 3],
            ['phd_id' => 63, 'cloud_id' => 0, 'phd_name' => 'Pediatrics', 'phd_parent_id' => 3],
            ['phd_id' => 64, 'cloud_id' => 0, 'phd_name' => 'Pharmacy', 'phd_parent_id' => 3],
            ['phd_id' => 65, 'cloud_id' => 0, 'phd_name' => 'Physics', 'phd_parent_id' => 3],
            ['phd_id' => 66, 'cloud_id' => 0, 'phd_name' => 'Plastics', 'phd_parent_id' => 3],
            ['phd_id' => 67, 'cloud_id' => 0, 'phd_name' => 'Production / Industrial', 'phd_parent_id' => 3],
            ['phd_id' => 68, 'cloud_id' => 0, 'phd_name' => 'Psychiatry', 'phd_parent_id' => 3],
            ['phd_id' => 69, 'cloud_id' => 0, 'phd_name' => 'Psychology', 'phd_parent_id' => 3],
            ['phd_id' => 70, 'cloud_id' => 0, 'phd_name' => 'Radiology', 'phd_parent_id' => 3],
            ['phd_id' => 71, 'cloud_id' => 0, 'phd_name' => 'Rheumatology', 'phd_parent_id' => 3],
            ['phd_id' => 72, 'cloud_id' => 0, 'phd_name' => 'Sanskrit', 'phd_parent_id' => 3],
            ['phd_id' => 73, 'cloud_id' => 0, 'phd_name' => 'Sociology', 'phd_parent_id' => 3],
            ['phd_id' => 74, 'cloud_id' => 0, 'phd_name' => 'Statistics', 'phd_parent_id' => 3],
            ['phd_id' => 75, 'cloud_id' => 0, 'phd_name' => 'Systems', 'phd_parent_id' => 3],
            ['phd_id' => 76, 'cloud_id' => 0, 'phd_name' => 'Textile', 'phd_parent_id' => 3],
            ['phd_id' => 77, 'cloud_id' => 0, 'phd_name' => 'Vocational Courses', 'phd_parent_id' => 3],
            ['phd_id' => 78, 'cloud_id' => 0, 'phd_name' => 'Other Arts', 'phd_parent_id' => 3],
            ['phd_id' => 79, 'cloud_id' => 0, 'phd_name' => 'Other Doctorate', 'phd_parent_id' => 3],
            ['phd_id' => 80, 'cloud_id' => 0, 'phd_name' => 'Other Engineering', 'phd_parent_id' => 3],
            ['phd_id' => 81, 'cloud_id' => 0, 'phd_name' => 'Other Management', 'phd_parent_id' => 3],
            ['phd_id' => 82, 'cloud_id' => 0, 'phd_name' => 'Other Science', 'phd_parent_id' => 3],
            ['phd_id' => 83, 'cloud_id' => 0, 'phd_name' => 'Other', 'phd_parent_id' => 3],
            ['phd_id' => 84, 'cloud_id' => 0, 'phd_name' => 'Advertising / Mass Communication', 'phd_parent_id' => 2],
            ['phd_id' => 85, 'cloud_id' => 0, 'phd_name' => 'Agriculture', 'phd_parent_id' => 2],
            ['phd_id' => 86, 'cloud_id' => 0, 'phd_name' => 'Anthropology', 'phd_parent_id' => 2],
            ['phd_id' => 87, 'cloud_id' => 0, 'phd_name' => 'Architecture', 'phd_parent_id' => 2],
            ['phd_id' => 88, 'cloud_id' => 0, 'phd_name' => 'Arts & Humanities', 'phd_parent_id' => 2],
            ['phd_id' => 89, 'cloud_id' => 0, 'phd_name' => 'Automobile', 'phd_parent_id' => 2],
            ['phd_id' => 90, 'cloud_id' => 0, 'phd_name' => 'Aviation', 'phd_parent_id' => 2],
            ['phd_id' => 91, 'cloud_id' => 0, 'phd_name' => 'Bio-Chemistry / Bio-Technology', 'phd_parent_id' => 2],
            ['phd_id' => 92, 'cloud_id' => 0, 'phd_name' => 'Biomedical', 'phd_parent_id' => 2],
            ['phd_id' => 93, 'cloud_id' => 0, 'phd_name' => 'Biotechnology', 'phd_parent_id' => 2],
            ['phd_id' => 94, 'cloud_id' => 0, 'phd_name' => 'Ceramics', 'phd_parent_id' => 2],
            ['phd_id' => 95, 'cloud_id' => 0, 'phd_name' => 'Chemical', 'phd_parent_id' => 2],
            ['phd_id' => 96, 'cloud_id' => 0, 'phd_name' => 'Chemistry', 'phd_parent_id' => 2],
            ['phd_id' => 97, 'cloud_id' => 0, 'phd_name' => 'Civil', 'phd_parent_id' => 2],
            ['phd_id' => 98, 'cloud_id' => 0, 'phd_name' => 'Commerce', 'phd_parent_id' => 2],
            ['phd_id' => 99, 'cloud_id' => 0, 'phd_name' => 'Communication', 'phd_parent_id' => 2],
            ['phd_id' => 100, 'cloud_id' => 0, 'phd_name' => 'Computers', 'phd_parent_id' => 2],
            ['phd_id' => 101, 'cloud_id' => 0, 'phd_name' => 'Dairy Technology', 'phd_parent_id' => 2],
            ['phd_id' => 102, 'cloud_id' => 0, 'phd_name' => 'Dermatology', 'phd_parent_id' => 2],
            ['phd_id' => 103, 'cloud_id' => 0, 'phd_name' => 'Economics', 'phd_parent_id' => 2],
            ['phd_id' => 104, 'cloud_id' => 0, 'phd_name' => 'Electrical', 'phd_parent_id' => 2],
            ['phd_id' => 105, 'cloud_id' => 0, 'phd_name' => 'Electronics / Telecommunication', 'phd_parent_id' => 2],
            ['phd_id' => 106, 'cloud_id' => 0, 'phd_name' => 'Energy', 'phd_parent_id' => 2],
            ['phd_id' => 107, 'cloud_id' => 0, 'phd_name' => 'ENT', 'phd_parent_id' => 2],
            ['phd_id' => 108, 'cloud_id' => 0, 'phd_name' => 'Environmental', 'phd_parent_id' => 2],
            ['phd_id' => 109, 'cloud_id' => 0, 'phd_name' => 'Fashion Designing / Other Designing', 'phd_parent_id' => 2],
            ['phd_id' => 110, 'cloud_id' => 0, 'phd_name' => 'Film', 'phd_parent_id' => 2],
            ['phd_id' => 111, 'cloud_id' => 0, 'phd_name' => 'Finance', 'phd_parent_id' => 2],
            ['phd_id' => 112, 'cloud_id' => 0, 'phd_name' => 'Fine arts', 'phd_parent_id' => 2],
            ['phd_id' => 113, 'cloud_id' => 0, 'phd_name' => 'Food Technology', 'phd_parent_id' => 2],
            ['phd_id' => 114, 'cloud_id' => 0, 'phd_name' => 'Hotel Management', 'phd_parent_id' => 2],
            ['phd_id' => 115, 'cloud_id' => 0, 'phd_name' => 'History', 'phd_parent_id' => 2],
            ['phd_id' => 116, 'cloud_id' => 0, 'phd_name' => 'HR / Industrial Relations', 'phd_parent_id' => 2],
            ['phd_id' => 117, 'cloud_id' => 0, 'phd_name' => 'Immunology', 'phd_parent_id' => 2],
            ['phd_id' => 118, 'cloud_id' => 0, 'phd_name' => 'International Business', 'phd_parent_id' => 2],
            ['phd_id' => 119, 'cloud_id' => 0, 'phd_name' => 'Instrumentation', 'phd_parent_id' => 2],
            ['phd_id' => 120, 'cloud_id' => 0, 'phd_name' => 'Journalism', 'phd_parent_id' => 2],
            ['phd_id' => 121, 'cloud_id' => 0, 'phd_name' => 'Law', 'phd_parent_id' => 2],
            ['phd_id' => 122, 'cloud_id' => 0, 'phd_name' => 'Literature', 'phd_parent_id' => 2],
            ['phd_id' => 123, 'cloud_id' => 0, 'phd_name' => 'Marine', 'phd_parent_id' => 2],
            ['phd_id' => 124, 'cloud_id' => 0, 'phd_name' => 'Marketing', 'phd_parent_id' => 2],
            ['phd_id' => 125, 'cloud_id' => 0, 'phd_name' => 'Maths', 'phd_parent_id' => 2],
            ['phd_id' => 126, 'cloud_id' => 0, 'phd_name' => 'Mechanical', 'phd_parent_id' => 2],
            ['phd_id' => 127, 'cloud_id' => 0, 'phd_name' => 'Medicine', 'phd_parent_id' => 2],
            ['phd_id' => 128, 'cloud_id' => 0, 'phd_name' => 'Metallurgy', 'phd_parent_id' => 2],
            ['phd_id' => 129, 'cloud_id' => 0, 'phd_name' => 'Microbiology', 'phd_parent_id' => 2],
            ['phd_id' => 130, 'cloud_id' => 0, 'phd_name' => 'Mineral', 'phd_parent_id' => 2],
            ['phd_id' => 131, 'cloud_id' => 0, 'phd_name' => 'Mining', 'phd_parent_id' => 2],
            ['phd_id' => 132, 'cloud_id' => 0, 'phd_name' => 'Neonatal', 'phd_parent_id' => 2],
            ['phd_id' => 133, 'cloud_id' => 0, 'phd_name' => 'Nuclear', 'phd_parent_id' => 2],
            ['phd_id' => 134, 'cloud_id' => 0, 'phd_name' => 'Obstretrics', 'phd_parent_id' => 2],
            ['phd_id' => 135, 'cloud_id' => 0, 'phd_name' => 'Paint / Oil', 'phd_parent_id' => 2],
            ['phd_id' => 136, 'cloud_id' => 0, 'phd_name' => 'Pathology', 'phd_parent_id' => 2],
            ['phd_id' => 137, 'cloud_id' => 0, 'phd_name' => 'Petroleum', 'phd_parent_id' => 2],
            ['phd_id' => 138, 'cloud_id' => 0, 'phd_name' => 'Pediatrics', 'phd_parent_id' => 2],
            ['phd_id' => 139, 'cloud_id' => 0, 'phd_name' => 'Pharmacy', 'phd_parent_id' => 2],
            ['phd_id' => 140, 'cloud_id' => 0, 'phd_name' => 'Physics', 'phd_parent_id' => 2],
            ['phd_id' => 141, 'cloud_id' => 0, 'phd_name' => 'Plastics', 'phd_parent_id' => 2],
            ['phd_id' => 142, 'cloud_id' => 0, 'phd_name' => 'Production / Industrial', 'phd_parent_id' => 2],
            ['phd_id' => 143, 'cloud_id' => 0, 'phd_name' => 'Psychiatry', 'phd_parent_id' => 2],
            ['phd_id' => 144, 'cloud_id' => 0, 'phd_name' => 'Psychology', 'phd_parent_id' => 2],
            ['phd_id' => 145, 'cloud_id' => 0, 'phd_name' => 'Radiology', 'phd_parent_id' => 2],
            ['phd_id' => 146, 'cloud_id' => 0, 'phd_name' => 'Rheumatology', 'phd_parent_id' => 2],
            ['phd_id' => 147, 'cloud_id' => 0, 'phd_name' => 'Sanskrit', 'phd_parent_id' => 2],
            ['phd_id' => 148, 'cloud_id' => 0, 'phd_name' => 'Sociology', 'phd_parent_id' => 2],
            ['phd_id' => 149, 'cloud_id' => 0, 'phd_name' => 'Statistics', 'phd_parent_id' => 2],
            ['phd_id' => 150, 'cloud_id' => 0, 'phd_name' => 'Systems', 'phd_parent_id' => 2],
            ['phd_id' => 151, 'cloud_id' => 0, 'phd_name' => 'Textile', 'phd_parent_id' => 2],
            ['phd_id' => 152, 'cloud_id' => 0, 'phd_name' => 'Vocational Courses', 'phd_parent_id' => 2],
            ['phd_id' => 153, 'cloud_id' => 0, 'phd_name' => 'Other Arts', 'phd_parent_id' => 2],
            ['phd_id' => 154, 'cloud_id' => 0, 'phd_name' => 'Other Doctorate', 'phd_parent_id' => 2],
            ['phd_id' => 155, 'cloud_id' => 0, 'phd_name' => 'Other Engineering', 'phd_parent_id' => 2],
            ['phd_id' => 156, 'cloud_id' => 0, 'phd_name' => 'Other Management', 'phd_parent_id' => 2],
            ['phd_id' => 157, 'cloud_id' => 0, 'phd_name' => 'Other Science', 'phd_parent_id' => 2],
            ['phd_id' => 158, 'cloud_id' => 0, 'phd_name' => 'Other', 'phd_parent_id' => 2],
            ['phd_id' => 159, 'cloud_id' => 0, 'phd_name' => 'Other Specialization', 'phd_parent_id' => 1],
            ['phd_id' => 166, 'cloud_id' => 1, 'phd_name' => 'fsadfasdfadsf', 'phd_parent_id' => 2],
            ['phd_id' => 168, 'cloud_id' => 1, 'phd_name' => 'fsadfadsfas', 'phd_parent_id' => 3],
            ['phd_id' => 170, 'cloud_id' => 1, 'phd_name' => 'fdsfdfdf', 'phd_parent_id' => 3],

        ]);
    }
}
